name: CI|CD

on:
    pull_request:
      branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                python-version: 3.6

            - name: Install tests dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r tests_requirements.txt

            - name: Run Black Check
              run: |
                black .

            - name: Run PyTest
              run: |
                pytest -vv